/**
 * Fallback data for when DATABASE_URL is not configured or DB is empty.
 * This ensures freedom-cosmetic-shop.vercel.app NEVER shows "No products found"
 * even if Postgres is not set up yet.
 * 
 * Data mirrored from scripts/seed.ts
 */

export const fallbackCategories = [
  {
    id: "cat_skincare",
    name: "Skincare",
    slug: "skincare",
    description: "Cleansers, moisturizers, serums & sunscreens for healthy, glowing skin.",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop",
    icon: "✨",
    parentId: null,
    sortOrder: 0,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { products: 6 },
  },
  {
    id: "cat_makeup",
    name: "Makeup",
    slug: "makeup",
    description: "Foundation, lipstick, eyeshadow & more — shades for every skin tone.",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop",
    icon: "💄",
    parentId: null,
    sortOrder: 1,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { products: 6 },
  },
  {
    id: "cat_haircare",
    name: "Haircare",
    slug: "haircare",
    description: "Shampoo, conditioner, oils & treatments for textured and coily hair.",
    image: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&auto=format&fit=crop",
    icon: "👩🏾‍🦱",
    parentId: null,
    sortOrder: 2,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    _count: { products: 6 },
  },
];

export const fallbackBrands = [
  { id: "brand_glow", name: "Freedom Glow", slug: "freedom-glow", description: "Skincare for radiant skin", logo: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=200&auto=format&fit=crop", country: "Rwanda" },
  { id: "brand_pure", name: "Freedom Pure", slug: "freedom-pure", description: "Gentle everyday essentials", logo: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=200&auto=format&fit=crop", country: "Rwanda" },
  { id: "brand_color", name: "Freedom Color", slug: "freedom-color", description: "Makeup for melanin-rich skin", logo: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&auto=format&fit=crop", country: "Rwanda" },
  { id: "brand_mane", name: "Freedom Mane", slug: "freedom-mane", description: "Haircare for textured hair", logo: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=200&auto=format&fit=crop", country: "Rwanda" },
];

const now = new Date().toISOString();

export const fallbackProducts = [
  // SKINCARE
  {
    id: "prod_vitc",
    name: "Vitamin C Brightening Serum",
    slug: "vitamin-c-brightening-serum",
    description: "A potent 15% Vitamin C serum that brightens dull skin, fades dark spots, and protects against pollution. Lightweight formula absorbs quickly. Apply 3-4 drops every morning before sunscreen.",
    shortDescription: "15% Vitamin C serum for bright, even-toned skin.",
    price: 12500,
    compareAt: 16000,
    costPrice: null,
    stock: 48,
    lowStockThreshold: 5,
    sku: "FC-VITC-30",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["ALL", "OILY", "COMBINATION"],
    shades: null,
    ingredients: ["Vitamin C (15%)", "Ferulic Acid", "Hyaluronic Acid", "Vitamin E"],
    size: "30ml",
    usageInstructions: "Apply 3-4 drops to clean skin every morning.",
    warnings: "Patch test before first use.",
    rating: 4.7,
    reviewsCount: 124,
    featured: true,
    isNew: true,
    isActive: true,
    categoryId: "cat_skincare",
    brandId: "brand_glow",
    category: fallbackCategories[0],
    brand: fallbackBrands[0],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_hya",
    name: "Hyaluronic Acid Hydrating Serum",
    slug: "hyaluronic-acid-hydrating-serum",
    description: "Deeply hydrating serum with multi-weight hyaluronic acid that plumps fine lines and locks in moisture for up to 72 hours. Non-comedogenic and fragrance-free.",
    shortDescription: "72-hour hydration for plump, smooth skin.",
    price: 9800,
    compareAt: null,
    costPrice: null,
    stock: 62,
    lowStockThreshold: 5,
    sku: "FC-HYA-30",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["ALL", "DRY", "SENSITIVE"],
    shades: null,
    ingredients: ["Hyaluronic Acid", "Panthenol", "Glycerin"],
    size: "30ml",
    usageInstructions: "Apply 2-3 drops to damp skin morning and night.",
    warnings: null,
    rating: 4.6,
    reviewsCount: 89,
    featured: true,
    isNew: true,
    isActive: true,
    categoryId: "cat_skincare",
    brandId: "brand_glow",
    category: fallbackCategories[0],
    brand: fallbackBrands[0],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_cleanser",
    name: "Gentle Foaming Cleanser",
    slug: "gentle-foaming-cleanser",
    description: "Sulphate-free foaming cleanser that removes makeup, dirt, and excess oil without stripping the skin barrier.",
    shortDescription: "Sulphate-free cleanser that won't strip your skin.",
    price: 6500,
    compareAt: null,
    costPrice: null,
    stock: 80,
    lowStockThreshold: 5,
    sku: "FC-CLN-150",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["ALL", "OILY"],
    shades: null,
    ingredients: ["Glycerin", "Aloe Vera", "Chamomile"],
    size: "150ml",
    usageInstructions: "Pump a small amount onto damp hands. Massage onto face.",
    warnings: null,
    rating: 4.5,
    reviewsCount: 156,
    featured: false,
    isNew: false,
    isActive: true,
    categoryId: "cat_skincare",
    brandId: "brand_pure",
    category: fallbackCategories[0],
    brand: fallbackBrands[1],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_sunscreen",
    name: "Mineral Sunscreen SPF 50",
    slug: "mineral-sunscreen-spf-50",
    description: "Broad-spectrum SPF 50 mineral sunscreen with zinc oxide. Leaves no white cast on dark skin tones. Water-resistant for up to 80 minutes.",
    shortDescription: "SPF 50 with zero white cast on dark skin.",
    price: 11200,
    compareAt: 14000,
    costPrice: null,
    stock: 35,
    lowStockThreshold: 5,
    sku: "FC-SPF-50",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1556228852-80b6e5eeff06?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["ALL"],
    shades: null,
    ingredients: ["Zinc Oxide 20%", "Niacinamide", "Green Tea"],
    size: "50ml",
    usageInstructions: "Apply generously 15 minutes before sun exposure.",
    warnings: "For external use only.",
    rating: 4.8,
    reviewsCount: 203,
    featured: true,
    isNew: true,
    isActive: true,
    categoryId: "cat_skincare",
    brandId: "brand_pure",
    category: fallbackCategories[0],
    brand: fallbackBrands[1],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_moist",
    name: "Daily Moisturizing Cream",
    slug: "daily-moisturizing-cream",
    description: "A lightweight yet deeply nourishing daily moisturizer with shea butter and ceramides. Strengthens the skin barrier.",
    shortDescription: "Shea butter + ceramides for a strong skin barrier.",
    price: 7800,
    compareAt: null,
    costPrice: null,
    stock: 95,
    lowStockThreshold: 5,
    sku: "FC-MOIST-50",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["DRY", "NORMAL"],
    shades: null,
    ingredients: ["Shea Butter", "Ceramides", "Glycerin"],
    size: "50ml",
    usageInstructions: "Apply pea-sized amount after serum.",
    warnings: null,
    rating: 4.4,
    reviewsCount: 78,
    featured: false,
    isNew: false,
    isActive: true,
    categoryId: "cat_skincare",
    brandId: "brand_glow",
    category: fallbackCategories[0],
    brand: fallbackBrands[0],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_night",
    name: "Overnight Repair Night Cream",
    slug: "overnight-repair-night-cream",
    description: "Rich night cream with retinol, peptides, and niacinamide that works while you sleep. Reduces fine lines, evens skin tone.",
    shortDescription: "Retinol night cream for smoother skin by morning.",
    price: 14200,
    compareAt: null,
    costPrice: null,
    stock: 28,
    lowStockThreshold: 5,
    sku: "FC-NIGHT-50",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["ALL", "DRY"],
    shades: null,
    ingredients: ["Retinol 0.3%", "Peptides", "Niacinamide"],
    size: "50ml",
    usageInstructions: "Apply at night. Start 2-3 nights per week.",
    warnings: "Do not use if pregnant.",
    rating: 4.6,
    reviewsCount: 67,
    featured: false,
    isNew: true,
    isActive: true,
    categoryId: "cat_skincare",
    brandId: "brand_glow",
    category: fallbackCategories[0],
    brand: fallbackBrands[0],
    createdAt: now,
    updatedAt: now,
  },
  // MAKEUP
  {
    id: "prod_found",
    name: "Full Coverage Foundation — Deep",
    slug: "full-coverage-foundation-deep",
    description: "Buildable medium-to-full coverage foundation with a natural matte finish. Formulated for melanin-rich skin tones — no ashiness, no oxidation. 16-hour wear.",
    shortDescription: "16-hour matte foundation for melanin-rich skin.",
    price: 15500,
    compareAt: 18500,
    costPrice: null,
    stock: 42,
    lowStockThreshold: 5,
    sku: "FC-FOUND-DEEP",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: ["ALL", "OILY"],
    shades: ["Light", "Medium", "Medium-Deep", "Deep", "Deep-Ebony", "Ebony"],
    ingredients: ["Hyaluronic Acid", "Vitamin E", "SPF 15"],
    size: "30ml",
    usageInstructions: "Apply with damp beauty sponge.",
    warnings: null,
    rating: 4.7,
    reviewsCount: 198,
    featured: true,
    isNew: false,
    isActive: true,
    categoryId: "cat_makeup",
    brandId: "brand_color",
    category: fallbackCategories[1],
    brand: fallbackBrands[2],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_lipstick",
    name: "Matte Liquid Lipstick — Mocha",
    slug: "matte-liquid-lipstick-mocha",
    description: "Highly pigmented liquid lipstick that dries to a comfortable matte finish. Transfer-proof and lasts through meals. Warm nude brown flatters deep skin.",
    shortDescription: "Transfer-proof matte lippie in warm nude brown.",
    price: 6800,
    compareAt: null,
    costPrice: null,
    stock: 110,
    lowStockThreshold: 5,
    sku: "FC-LIP-MOCHA",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: ["Mocha", "Berry", "Crimson", "Nude", "Plum", "Coral"],
    ingredients: ["Vitamin E", "Jojoba Oil", "Castor Oil"],
    size: "6ml",
    usageInstructions: "Apply to clean, dry lips. Allow 60 seconds to dry.",
    warnings: null,
    rating: 4.5,
    reviewsCount: 234,
    featured: true,
    isNew: true,
    isActive: true,
    categoryId: "cat_makeup",
    brandId: "brand_color",
    category: fallbackCategories[1],
    brand: fallbackBrands[2],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_mascara",
    name: "Volumizing Mascara — Black",
    slug: "volumizing-mascara-black",
    description: "Lash-doubling mascara with curved brush that lifts, curls, and volumizes in one coat. Smudge-proof and flake-free.",
    shortDescription: "Lash-doubling mascara, smudge-proof all day.",
    price: 7200,
    compareAt: null,
    costPrice: null,
    stock: 88,
    lowStockThreshold: 5,
    sku: "FC-MASC-BLACK",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1631214540242-3cd8c4b0b3b6?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: ["Black", "Brown-Black"],
    ingredients: ["Beeswax", "Carnauba Wax", "Panthenol"],
    size: "10ml",
    usageInstructions: "Wiggle brush from root to tip.",
    warnings: null,
    rating: 4.4,
    reviewsCount: 145,
    featured: false,
    isNew: false,
    isActive: true,
    categoryId: "cat_makeup",
    brandId: "brand_color",
    category: fallbackCategories[1],
    brand: fallbackBrands[2],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_eyeshadow",
    name: "Eyeshadow Palette — Earth Tones",
    slug: "eyeshadow-palette-earth-tones",
    description: "12-shade eyeshadow palette with matte and shimmer finishes. Warm browns, coppers, and golds that pop on dark skin.",
    shortDescription: "12 warm shades that pop on melanin-rich skin.",
    price: 13500,
    compareAt: 16500,
    costPrice: null,
    stock: 36,
    lowStockThreshold: 5,
    sku: "FC-EYE-EARTH",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1583241800698-9c2e6b0f7c0a?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Mica", "Talc", "Magnesium Stearate"],
    size: "12 × 1.5g",
    usageInstructions: "Apply with eyeshadow brush.",
    warnings: null,
    rating: 4.6,
    reviewsCount: 112,
    featured: true,
    isNew: true,
    isActive: true,
    categoryId: "cat_makeup",
    brandId: "brand_color",
    category: fallbackCategories[1],
    brand: fallbackBrands[2],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_blush",
    name: "Soft Matte Blush — Rosewood",
    slug: "soft-matte-blush-rosewood",
    description: "Silky powder blush that adds a natural flush. Deep berry-rose shows up beautifully on melanin-rich skin.",
    shortDescription: "Berry-rose blush for a natural flush on dark skin.",
    price: 5900,
    compareAt: null,
    costPrice: null,
    stock: 70,
    lowStockThreshold: 5,
    sku: "FC-BLUSH-ROSE",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1599733589046-8a35aa3271c8?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: ["Rosewood", "Berry", "Coral", "Plum"],
    ingredients: ["Mica", "Vitamin E", "Talc"],
    size: "4g",
    usageInstructions: "Apply to apples of cheeks.",
    warnings: null,
    rating: 4.3,
    reviewsCount: 87,
    featured: false,
    isNew: false,
    isActive: true,
    categoryId: "cat_makeup",
    brandId: "brand_color",
    category: fallbackCategories[1],
    brand: fallbackBrands[2],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_gloss",
    name: "High-Shine Lip Gloss — Honey",
    slug: "high-shine-lip-gloss-honey",
    description: "Non-sticky lip gloss with mirror-like shine. Sheer golden nude works on all skin tones. Infused with jojoba oil.",
    shortDescription: "Mirror-shine gloss infused with jojoba oil.",
    price: 5200,
    compareAt: null,
    costPrice: null,
    stock: 125,
    lowStockThreshold: 5,
    sku: "FC-GLOSS-HONEY",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1599751449628-9d4a93b3f0a1?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: ["Honey", "Clear", "Rose", "Mauve"],
    ingredients: ["Jojoba Oil", "Castor Oil", "Vitamin E"],
    size: "8ml",
    usageInstructions: "Apply directly to lips.",
    warnings: null,
    rating: 4.5,
    reviewsCount: 96,
    featured: false,
    isNew: true,
    isActive: true,
    categoryId: "cat_makeup",
    brandId: "brand_color",
    category: fallbackCategories[1],
    brand: fallbackBrands[2],
    createdAt: now,
    updatedAt: now,
  },
  // HAIRCARE
  {
    id: "prod_shampoo",
    name: "Sulfate-Free Shampoo — Curl Care",
    slug: "sulfate-free-shampoo-curl-care",
    description: "Gentle sulfate-free shampoo that cleanses without stripping natural oils. For curly, coily, textured hair. Argan oil + shea butter.",
    shortDescription: "Sulfate-free shampoo for curly & coily hair.",
    price: 8900,
    compareAt: null,
    costPrice: null,
    stock: 56,
    lowStockThreshold: 5,
    sku: "FC-SHAMP-CURL",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Argan Oil", "Shea Butter", "Aloe Vera"],
    size: "300ml",
    usageInstructions: "Wet hair thoroughly. Massage into scalp. Rinse.",
    warnings: null,
    rating: 4.6,
    reviewsCount: 167,
    featured: true,
    isNew: false,
    isActive: true,
    categoryId: "cat_haircare",
    brandId: "brand_mane",
    category: fallbackCategories[2],
    brand: fallbackBrands[3],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_cond",
    name: "Deep Conditioner — Moisture Lock",
    slug: "deep-conditioner-moisture-lock",
    description: "Rich, creamy deep conditioner that restores moisture and slip to textured hair. Use weekly for 15-30 minutes under warm cap.",
    shortDescription: "Weekly deep conditioning for moisture & slip.",
    price: 9500,
    compareAt: 11500,
    costPrice: null,
    stock: 44,
    lowStockThreshold: 5,
    sku: "FC-COND-MOIST",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Hydrolyzed Protein", "Panthenol", "Shea Butter"],
    size: "250ml",
    usageInstructions: "After shampooing, apply generously. Leave 15-30 minutes.",
    warnings: null,
    rating: 4.7,
    reviewsCount: 142,
    featured: true,
    isNew: true,
    isActive: true,
    categoryId: "cat_haircare",
    brandId: "brand_mane",
    category: fallbackCategories[2],
    brand: fallbackBrands[3],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_oil",
    name: "Hair Growth Oil — Rosemary & Peppermint",
    slug: "hair-growth-oil-rosemary-peppermint",
    description: "Stimulating scalp oil blend with rosemary, peppermint, and castor oil. Promotes healthy hair growth and reduces shedding. Massage 2-3x per week.",
    shortDescription: "Rosemary + castor oil for healthy hair growth.",
    price: 7800,
    compareAt: null,
    costPrice: null,
    stock: 78,
    lowStockThreshold: 5,
    sku: "FC-OIL-GROWTH",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1607602132700-068258431c6c?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Rosemary Oil", "Peppermint Oil", "Castor Oil", "Biotin"],
    size: "100ml",
    usageInstructions: "Part hair and apply drops to scalp. Massage 5 minutes.",
    warnings: "Patch test before use.",
    rating: 4.8,
    reviewsCount: 289,
    featured: true,
    isNew: false,
    isActive: true,
    categoryId: "cat_haircare",
    brandId: "brand_mane",
    category: fallbackCategories[2],
    brand: fallbackBrands[3],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_curl",
    name: "Curl Defining Cream",
    slug: "curl-defining-cream",
    description: "Leave-in cream that defines curls and coils without crunch. Provides hold, shine, and frizz control for up to 3 days.",
    shortDescription: "Frizz-free curl definition for 3 days.",
    price: 8200,
    compareAt: null,
    costPrice: null,
    stock: 52,
    lowStockThreshold: 5,
    sku: "FC-CURL-CREAM",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Shea Butter", "Aloe Vera", "Jojoba Oil"],
    size: "250ml",
    usageInstructions: "Apply to damp, sectioned hair. Rake through and scrunch.",
    warnings: null,
    rating: 4.5,
    reviewsCount: 134,
    featured: false,
    isNew: true,
    isActive: true,
    categoryId: "cat_haircare",
    brandId: "brand_mane",
    category: fallbackCategories[2],
    brand: fallbackBrands[3],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_mask",
    name: "Intensive Hair Mask — Repair",
    slug: "intensive-hair-mask-repair",
    description: "Protein-rich hair mask that repairs heat and chemical damage. Use every 2 weeks in place of conditioner. Keratin + biotin + avocado oil.",
    shortDescription: "Keratin + biotin mask for damaged hair.",
    price: 11800,
    compareAt: 14000,
    costPrice: null,
    stock: 38,
    lowStockThreshold: 5,
    sku: "FC-MASK-REPAIR",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1631730486572-226d1f595b68?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Keratin", "Biotin", "Avocado Oil", "Argan Oil"],
    size: "250g",
    usageInstructions: "Apply to clean, damp hair. Leave 20-30 minutes.",
    warnings: null,
    rating: 4.6,
    reviewsCount: 98,
    featured: false,
    isNew: false,
    isActive: true,
    categoryId: "cat_haircare",
    brandId: "brand_mane",
    category: fallbackCategories[2],
    brand: fallbackBrands[3],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "prod_edge",
    name: "Edge Control Gel — Strong Hold",
    slug: "edge-control-gel-strong-hold",
    description: "Long-lasting edge control gel that lays baby hairs flat without flaking. Strong 24-hour hold. Adds shine. Non-greasy.",
    shortDescription: "24-hour edge hold, zero flaking.",
    price: 4800,
    compareAt: null,
    costPrice: null,
    stock: 92,
    lowStockThreshold: 5,
    sku: "FC-EDGE-STRONG",
    barcode: null,
    images: ["https://images.unsplash.com/photo-1607602132700-068258431c6c?w=800&auto=format&fit=crop"],
    videoUrl: null,
    skinType: null,
    shades: null,
    ingredients: ["Aloe Vera", "Castor Oil", "Panthenol"],
    size: "113g",
    usageInstructions: "Apply small amount to edges with small brush.",
    warnings: null,
    rating: 4.4,
    reviewsCount: 156,
    featured: false,
    isNew: false,
    isActive: true,
    categoryId: "cat_haircare",
    brandId: "brand_mane",
    category: fallbackCategories[2],
    brand: fallbackBrands[3],
    createdAt: now,
    updatedAt: now,
  },
];
