import Image from 'next/image'

type BrandMarkVariant = 'icon' | 'badge'

const SOURCES: Record<BrandMarkVariant, string> = {
  // 512px master, used wherever the mark is rendered at 32px or larger.
  icon: '/logo-icon.png',
  // 128px silhouette tuned to stay legible down to 24px.
  badge: '/logo-badge.png',
}

export type BrandMarkProps = {
  /** `badge` for 24-32px chrome, `icon` everywhere else. */
  variant?: BrandMarkVariant
  /** Rendered square size in CSS pixels. */
  size?: number
  className?: string
  /** Above-the-fold marks (header, auth panel) should set this. */
  priority?: boolean
  /**
   * Decorative by default: these marks nearly always sit beside the words
   * "FreedomCosmeticShop", and a duplicate alt makes screen readers announce
   * the brand twice. Pass an explicit alt when the mark stands alone.
   */
  alt?: string
}

/**
 * The FreedomCosmeticShop flower mark.
 *
 * One component so the logo cannot drift out of sync across the storefront,
 * the admin panel, auth and checkout. Assets are generated by
 * `brand-src/build-brand-assets.py` — see `brand-src/README.md`.
 */
export default function BrandMark({
  variant = 'icon',
  size = 40,
  className,
  priority = false,
  alt,
}: BrandMarkProps) {
  return (
    <Image
      src={SOURCES[variant]}
      alt={alt ?? ''}
      aria-hidden={alt ? undefined : true}
      width={size}
      height={size}
      priority={priority}
      className={className}
    />
  )
}
