'use client'

import { useState, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import { Eye, EyeOff, Loader2, Lock, ShieldCheck } from 'lucide-react'
import { useStore } from '@/store/useStore'

export default function ChangePasswordPage() {
  const router=useRouter();const user=useStore((state)=>state.user);const fetchUser=useStore((state)=>state.fetchUser)
  const[currentPassword,setCurrentPassword]=useState('');const[newPassword,setNewPassword]=useState('');const[confirm,setConfirm]=useState('');const[visible,setVisible]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState<string|null>(null)
  const submit=async(event:FormEvent)=>{event.preventDefault();setError(null);if(newPassword!==confirm){setError('New passwords do not match');return}setLoading(true);try{const response=await fetch('/api/user/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.error||'Password change failed');await fetchUser();const role=useStore.getState().user?.role;router.replace(['ADMIN','SUPER_ADMIN','STAFF','MANAGER'].includes(role||'')?'/admin':'/account');router.refresh()}catch(reason){setError(reason instanceof Error?reason.message:'Password change failed')}finally{setLoading(false)}}
  return <main className="grid min-h-dvh place-items-center bg-gradient-to-br from-[#1a1a1a] via-[#2d2426] to-[#6f4249] px-4 py-10"><div className="w-full max-w-md rounded-[2rem] bg-white p-6 shadow-2xl sm:p-8"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-rose-50 text-[#B76E79]"><ShieldCheck className="h-7 w-7" /></span><h1 className="mt-5 text-center text-2xl font-black">Change your password</h1><p className="mt-2 text-center text-sm leading-6 text-gray-500">{user?.mustChangePassword?'Your temporary password must be replaced before continuing.':'Choose a unique password you do not use elsewhere.'}</p>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-center text-sm font-semibold text-red-700" role="alert">{error}</p>}<form onSubmit={submit} className="mt-6 space-y-4"><Password label="Current password" value={currentPassword} setValue={setCurrentPassword} visible={visible} /><Password label="New password" value={newPassword} setValue={setNewPassword} visible={visible} /><Password label="Confirm new password" value={confirm} setValue={setConfirm} visible={visible} /><button type="button" onClick={()=>setVisible((value)=>!value)} className="flex items-center gap-1 text-xs font-bold text-gray-500">{visible?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}{visible?'Hide passwords':'Show passwords'}</button><div className="rounded-xl bg-gray-50 p-3 text-xs leading-5 text-gray-600">Use at least 12 characters with uppercase, lowercase, number, and symbol.</div><button type="submit" disabled={loading||!currentPassword||!newPassword||!confirm} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#B76E79] text-sm font-black text-white disabled:opacity-50">{loading?<><Loader2 className="h-4 w-4 animate-spin"/>Updating…</>:'Change password'}</button></form></div></main>
}
function Password({label,value,setValue,visible}:{label:string;value:string;setValue:(value:string)=>void;visible:boolean}){return <label className="block"><span className="mb-1.5 block text-xs font-black uppercase tracking-wider text-gray-500">{label}</span><div className="relative"><Lock className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400"/><input type={visible?'text':'password'} value={value} onChange={(event)=>setValue(event.target.value)} autoComplete={label==='Current password'?'current-password':'new-password'} className="input-field pl-10" required /></div></label>}
