'use client'

import { useCallback, useEffect, useState } from 'react'
import { Eye, EyeOff, Flag, Loader2, MessageSquare, Star } from 'lucide-react'
import { useT } from '@/lib/i18n/LanguageContext'
import { useToast } from '@/hooks/use-toast'

type Tab = 'all' | 'reported' | 'needs_response' | 'hidden'
interface AdminReview {
  id: string; rating: number; title: string | null; body: string | null; isVerified: boolean; isHidden: boolean; moderationReason: string | null; merchantResponse: string | null; merchantResponseAt: string | null; orderNumber: string | null; createdAt: string; user: { name: string } | null; product: { name: string; slug: string }; reports: Array<{ id: string; reason: string; createdAt: string }>
}
const tabs: Tab[] = ['all','reported','needs_response','hidden']
const moderationReasons = ['SPAM','ABUSE','PRIVACY','LEGAL','DUPLICATE'] as const

export default function AdminReviewsView() {
  const t = useT(); const { toast } = useToast()
  const [tab, setTab] = useState<Tab>('all'); const [reviews, setReviews] = useState<AdminReview[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false)
  const [responding, setResponding] = useState<string | null>(null); const [response, setResponse] = useState('')
  const [moderating, setModerating] = useState<string | null>(null); const [reason, setReason] = useState<(typeof moderationReasons)[number]>('SPAM'); const [details, setDetails] = useState('')
  const load = useCallback(async () => { setLoading(true); setFailed(false); try { const res = await fetch(`/api/admin/reviews?filter=${tab}`, { cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(); setReviews(data.data?.reviews || []) } catch { setFailed(true) } finally { setLoading(false) } }, [tab])
  useEffect(() => { void load() }, [load])

  const respond = async (id: string) => { const res = await fetch(`/api/admin/reviews/${id}/respond`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ response }) }); if (res.ok) { toast({ title: t('reviews.admin_response_saved') }); setResponding(null); setResponse(''); void load() } else toast({ title: t('reviews.admin_action_failed'), variant: 'destructive' }) }
  const moderate = async (id: string, action: 'HIDE' | 'RESTORE') => { const res = await fetch(`/api/admin/reviews/${id}/hide`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(action === 'HIDE' ? { action, reason, details: details.trim() || undefined } : { action }) }); if (res.ok) { toast({ title: action === 'HIDE' ? t('reviews.admin_hidden') : t('reviews.admin_restored') }); setModerating(null); setDetails(''); void load() } else toast({ title: t('reviews.admin_action_failed'), variant: 'destructive' }) }
  const resolveReports = async (id: string) => { const res = await fetch(`/api/admin/reviews/${id}/resolve-reports`, { method: 'POST' }); if (res.ok) { toast({ title: t('reviews.admin_reports_resolved') }); void load() } else toast({ title: t('reviews.admin_action_failed'), variant: 'destructive' }) }

  return <main className="space-y-6"><header><h1 className="text-2xl font-black text-gray-900">{t('reviews.admin_title')}</h1><p className="mt-1 text-sm text-gray-500">{t('reviews.admin_subtitle')}</p></header><section className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><h2 className="text-sm font-black text-blue-900">{t('reviews.admin_guidelines')}</h2><ul className="mt-2 list-inside list-disc space-y-1 text-xs leading-5 text-blue-800"><li>{t('reviews.admin_keep_negative')}</li><li>{t('reviews.admin_hide_only_abuse')}</li><li>{t('reviews.admin_respond_professionally')}</li><li>{t('reviews.admin_no_rating_bias')}</li></ul></section>
    <nav className="flex gap-2 overflow-x-auto border-b" aria-label={t('reviews.admin_filters')}>{tabs.map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`min-h-11 shrink-0 border-b-2 px-4 text-sm font-bold ${tab === item ? 'border-[#B76E79] text-[#B76E79]' : 'border-transparent text-gray-500'}`}>{t(`reviews.admin_tab_${item}`)}</button>)}</nav>
    {loading ? <div className="py-12 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#B76E79]" /></div> : failed ? <div className="rounded-2xl border border-dashed p-8 text-center"><p>{t('reviews.admin_load_failed')}</p><button type="button" onClick={load} className="mt-3 min-h-11 rounded-xl bg-gray-900 px-4 font-bold text-white">{t('common.retry')}</button></div> : reviews.length === 0 ? <p className="rounded-2xl bg-gray-50 p-8 text-center text-sm text-gray-500">{t('reviews.admin_empty')}</p> : <div className="space-y-4">{reviews.map((review) => <article key={review.id} className={`rounded-2xl border bg-white p-5 ${review.isHidden ? 'border-amber-300' : 'border-gray-100'}`}><header className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><strong>{review.user?.name || t('checkout.customer')}</strong>{review.isVerified && <span className="rounded-full bg-green-50 px-2 py-1 text-xs font-bold text-green-700">{t('reviews.verified_purchase')}</span>}{review.isHidden && <span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-700">{t('reviews.admin_hidden_label')}</span>}</div><p className="mt-1 text-xs text-gray-500">{review.product.name} · {review.orderNumber || t('reviews.admin_order_unavailable')}</p><span className="mt-2 flex">{[1,2,3,4,5].map((star) => <Star key={star} className={`h-4 w-4 ${star <= review.rating ? 'fill-yellow-400 text-yellow-400' : 'fill-gray-100 text-gray-300'}`} />)}</span></div><time className="text-xs text-gray-400">{new Date(review.createdAt).toLocaleDateString('en-RW', { dateStyle: 'medium' })}</time></header>{review.title && <h2 className="mt-3 font-black">{review.title}</h2>}{review.body && <p className="mt-2 whitespace-pre-line text-sm leading-6 text-gray-700">{review.body}</p>}
      {review.reports.length > 0 && <section className="mt-4 rounded-xl bg-red-50 p-3"><h3 className="flex items-center gap-1 text-xs font-black text-red-800"><Flag className="h-4 w-4" />{t('reviews.admin_open_reports', { count: review.reports.length })}</h3><ul className="mt-1 space-y-1 text-xs text-red-700">{review.reports.map((report) => <li key={report.id}>{report.reason}</li>)}</ul><button type="button" onClick={() => resolveReports(review.id)} className="mt-2 min-h-11 rounded-xl bg-white px-3 text-xs font-bold text-gray-700">{t('reviews.admin_keep_visible')}</button></section>}
      {review.merchantResponse ? <section className="mt-4 rounded-xl border-l-4 border-[#B76E79] bg-gray-50 p-3"><strong className="text-xs">{t('reviews.merchant_response')}</strong><p className="mt-1 text-sm">{review.merchantResponse}</p></section> : responding === review.id ? <section className="mt-4"><textarea value={response} onChange={(event) => setResponse(event.target.value)} maxLength={2000} rows={3} placeholder={t('reviews.admin_response_placeholder')} className="input-field resize-none" /><div className="mt-2 flex gap-2"><button type="button" onClick={() => respond(review.id)} disabled={response.trim().length < 3} className="min-h-11 rounded-xl bg-[#B76E79] px-4 text-sm font-bold text-white disabled:opacity-40">{t('reviews.admin_post_response')}</button><button type="button" onClick={() => { setResponding(null); setResponse('') }} className="min-h-11 rounded-xl border px-4 text-sm font-bold">{t('common.cancel')}</button></div></section> : <button type="button" onClick={() => setResponding(review.id)} className="mt-4 flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-bold text-[#B76E79]"><MessageSquare className="h-4 w-4" />{t('reviews.admin_respond')}</button>}
      <footer className="mt-4 border-t pt-3">{review.isHidden ? <button type="button" onClick={() => moderate(review.id, 'RESTORE')} className="flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-bold text-green-700"><Eye className="h-4 w-4" />{t('reviews.admin_restore')}</button> : moderating === review.id ? <div className="rounded-xl bg-amber-50 p-3"><p className="text-xs font-bold text-amber-900">{t('reviews.admin_hide_reason')}</p><select value={reason} onChange={(event) => setReason(event.target.value as typeof reason)} className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3">{moderationReasons.map((item) => <option key={item} value={item}>{t(`reviews.admin_reason_${item.toLowerCase()}`)}</option>)}</select><textarea value={details} onChange={(event) => setDetails(event.target.value)} maxLength={500} placeholder={t('reviews.admin_moderation_details')} className="input-field mt-2 resize-none" /><div className="mt-2 flex gap-2"><button type="button" onClick={() => moderate(review.id, 'HIDE')} className="min-h-11 rounded-xl bg-amber-700 px-4 text-sm font-bold text-white">{t('reviews.admin_confirm_hide')}</button><button type="button" onClick={() => setModerating(null)} className="min-h-11 rounded-xl border px-4 text-sm font-bold">{t('common.cancel')}</button></div></div> : <button type="button" onClick={() => setModerating(review.id)} className="flex min-h-11 items-center gap-2 rounded-xl px-3 text-sm font-bold text-amber-700"><EyeOff className="h-4 w-4" />{t('reviews.admin_hide_spam')}</button>}</footer></article>)}</div>}
  </main>
}
