'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { Edit2, Eye, Loader2, Plus, Trash2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useToast } from '@/hooks/use-toast'
import { useT } from '@/lib/i18n/LanguageContext'
import { formatRWF } from '@/lib/format'

interface AdminProduct { id: string; name: string; price: number; stock: number }
interface BundleProductForm { productId: string; stepOrder: number; stepLabel: string; stepLabelRw: string; quantity: number; isOptional: boolean }
interface AdminBundle { id: string; name: string; nameRw?: string | null; slug: string; description?: string | null; descriptionRw?: string | null; bundleType: string; bundlePrice: number; normalTotal: number; savings: number; isActive: boolean; isFeatured: boolean; isInStock: boolean; totalSales: number; coverImage?: string | null; coverImageUrl?: string | null; targetConcern?: string | null; targetSkinType?: string | null; targetHairType?: string | null; targetCategory?: string | null; usageInstructions?: string | null; usageInstructionsRw?: string | null; products: Array<BundleProductForm & { id: string; product: AdminProduct }> }
interface FormState { id?: string; name: string; nameRw: string; slug: string; description: string; descriptionRw: string; bundleType: string; bundlePrice: string; coverImage: string; coverImageUrl: string; isActive: boolean; isFeatured: boolean; targetConcern: string; targetSkinType: string; targetHairType: string; targetCategory: string; usageInstructions: string; usageInstructionsRw: string; products: BundleProductForm[] }
const EMPTY: FormState = { name: '', nameRw: '', slug: '', description: '', descriptionRw: '', bundleType: 'ROUTINE', bundlePrice: '0', coverImage: '', coverImageUrl: '', isActive: true, isFeatured: false, targetConcern: '', targetSkinType: '', targetHairType: '', targetCategory: '', usageInstructions: '', usageInstructionsRw: '', products: [] }
const TYPES = ['ROUTINE', 'CONCERN', 'HAIR', 'MAKEUP', 'GIFT', 'STARTER']

export default function BundleManager() {
  const t = useT(); const { toast } = useToast()
  const [bundles, setBundles] = useState<AdminBundle[]>([]); const [products, setProducts] = useState<AdminProduct[]>([])
  const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [form, setForm] = useState<FormState>(EMPTY)
  const load = useCallback(async () => { setLoading(true); try { const [bundleResponse, productResponse] = await Promise.all([fetch('/api/admin/bundles', { cache: 'no-store' }), fetch('/api/admin/products?pageSize=100', { cache: 'no-store' })]); if (!bundleResponse.ok || !productResponse.ok) throw new Error(); const bundleData = await bundleResponse.json(); const productData = await productResponse.json(); setBundles(bundleData.data || []); setProducts((productData.products || []).map((product: AdminProduct) => ({ id: product.id, name: product.name, price: product.price, stock: product.stock }))) } catch { toast({ title: t('bundles.admin_load_failed'), variant: 'destructive' }) } finally { setLoading(false) } }, [t, toast])
  useEffect(() => { void load() }, [load])
  const edit = (bundle: AdminBundle) => { setForm({ id: bundle.id, name: bundle.name, nameRw: bundle.nameRw || '', slug: bundle.slug, description: bundle.description || '', descriptionRw: bundle.descriptionRw || '', bundleType: bundle.bundleType, bundlePrice: String(bundle.bundlePrice), coverImage: bundle.coverImage || '', coverImageUrl: bundle.coverImageUrl || '', isActive: bundle.isActive, isFeatured: bundle.isFeatured, targetConcern: bundle.targetConcern || '', targetSkinType: bundle.targetSkinType || '', targetHairType: bundle.targetHairType || '', targetCategory: bundle.targetCategory || '', usageInstructions: bundle.usageInstructions || '', usageInstructionsRw: bundle.usageInstructionsRw || '', products: bundle.products.map((item) => ({ productId: item.productId, stepOrder: item.stepOrder, stepLabel: item.stepLabel || '', stepLabelRw: item.stepLabelRw || '', quantity: item.quantity, isOptional: item.isOptional })) }); setOpen(true) }
  const toggleProduct = (productId: string) => setForm((current) => current.products.some((item) => item.productId === productId) ? { ...current, products: current.products.filter((item) => item.productId !== productId) } : { ...current, products: [...current.products, { productId, stepOrder: current.products.length + 1, stepLabel: '', stepLabelRw: '', quantity: 1, isOptional: false }] })
  const updateProduct = (productId: string, updates: Partial<BundleProductForm>) => setForm((current) => ({ ...current, products: current.products.map((item) => item.productId === productId ? { ...item, ...updates } : item) }))
  const upload = async (file?: File) => { if (!file) return; setUploading(true); try { const body = new FormData(); body.set('file', file); body.set('folder', 'bundles'); const response = await fetch('/api/upload', { method: 'POST', body }); const result = await response.json(); if (!response.ok) throw new Error(result.error); const image = result.image || result.data?.image; setForm((current) => ({ ...current, coverImage: image.publicId, coverImageUrl: image.url })) } catch { toast({ title: t('bundles.admin_upload_failed'), variant: 'destructive' }) } finally { setUploading(false) } }
  const save = async () => { if (!form.name.trim() || form.products.length === 0 || Number(form.bundlePrice) < 0) { toast({ title: t('bundles.admin_required'), variant: 'destructive' }); return } setSaving(true); try { const payload = { ...form, bundlePrice: Number(form.bundlePrice), nameRw: form.nameRw || null, description: form.description || null, descriptionRw: form.descriptionRw || null, coverImage: form.coverImage || null, coverImageUrl: form.coverImageUrl || null, targetConcern: form.targetConcern || null, targetSkinType: form.targetSkinType || null, targetHairType: form.targetHairType || null, targetCategory: form.targetCategory || null, usageInstructions: form.usageInstructions || null, usageInstructionsRw: form.usageInstructionsRw || null, products: form.products.map((item) => ({ ...item, stepLabel: item.stepLabel || null, stepLabelRw: item.stepLabelRw || null })) }; const response = await fetch(form.id ? `/api/admin/bundles/${form.id}` : '/api/admin/bundles', { method: form.id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); toast({ title: form.id ? t('bundles.admin_updated') : t('bundles.admin_created') }); setOpen(false); setForm(EMPTY); await load() } catch (error) { toast({ title: t('bundles.admin_save_failed'), description: error instanceof Error ? error.message : undefined, variant: 'destructive' }) } finally { setSaving(false) } }
  const remove = async (bundle: AdminBundle) => { if (!window.confirm(t('bundles.admin_delete_confirm', { bundle: bundle.name }))) return; const response = await fetch(`/api/admin/bundles/${bundle.id}`, { method: 'DELETE' }); if (response.ok) { toast({ title: t('bundles.admin_deleted') }); await load() } else toast({ title: t('bundles.admin_delete_failed'), variant: 'destructive' }) }

  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{t('bundles.admin_title')}</h2><p className="text-sm text-gray-500">{t('bundles.admin_count', { count: bundles.length })}</p></div><Button onClick={() => { setForm(EMPTY); setOpen(true) }}><Plus className="mr-2 h-4 w-4" />{t('bundles.admin_create')}</Button></div>
    {loading ? <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin" /></div> : bundles.length === 0 ? <p className="rounded-2xl border border-dashed p-10 text-center text-sm text-gray-500">{t('bundles.admin_empty')}</p> : <div className="space-y-3">{bundles.map((bundle) => <article key={bundle.id} className="flex flex-wrap items-center gap-3 rounded-2xl border bg-white p-4"><div className="min-w-0 flex-1"><h3 className="truncate font-bold">{bundle.name}</h3><p className="text-xs text-gray-500">{bundle.products.length} · {formatRWF(bundle.bundlePrice)} · {t('bundles.you_save')} {formatRWF(Math.max(0, bundle.savings))}</p><p className="mt-1 text-xs text-gray-400">{t('bundles.admin_sales', { count: bundle.totalSales })}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${bundle.isInStock ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700'}`}>{bundle.isInStock ? t('bundles.in_stock') : t('common.sold_out')}</span><div className="flex gap-1"><Link href={`/bundles/${bundle.slug}`} target="_blank" className="grid h-11 w-11 place-items-center rounded-xl hover:bg-gray-50" aria-label={t('common.view')}><Eye className="h-4 w-4" /></Link><button type="button" onClick={() => edit(bundle)} className="grid h-11 w-11 place-items-center rounded-xl hover:bg-gray-50" aria-label={t('common.edit')}><Edit2 className="h-4 w-4" /></button><button type="button" onClick={() => remove(bundle)} className="grid h-11 w-11 place-items-center rounded-xl text-red-600 hover:bg-red-50" aria-label={t('common.delete')}><Trash2 className="h-4 w-4" /></button></div></article>)}</div>}

    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{form.id ? t('bundles.admin_edit') : t('bundles.admin_create')}</DialogTitle></DialogHeader><div className="space-y-5">
      <div className="grid gap-3 sm:grid-cols-2"><Field label={t('bundles.admin_name')}><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label={t('bundles.admin_name_rw')}><Input value={form.nameRw} onChange={(e) => setForm({ ...form, nameRw: e.target.value })} /></Field><Field label={t('bundles.admin_slug')}><Input value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} /></Field><Field label={t('bundles.admin_type')}><Select value={form.bundleType} onValueChange={(value) => setForm({ ...form, bundleType: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{TYPES.map((type) => <SelectItem key={type} value={type}>{t(`bundles.type_${type.toLowerCase()}`)}</SelectItem>)}</SelectContent></Select></Field><Field label={t('bundles.bundle_price')}><Input type="number" min="0" value={form.bundlePrice} onChange={(e) => setForm({ ...form, bundlePrice: e.target.value })} /></Field><Field label={t('bundles.admin_target_category')}><Input value={form.targetCategory} onChange={(e) => setForm({ ...form, targetCategory: e.target.value })} /></Field><Field label={t('bundles.admin_target_concern')}><Input value={form.targetConcern} onChange={(e) => setForm({ ...form, targetConcern: e.target.value })} /></Field><Field label={t('bundles.admin_target_skin')}><Input value={form.targetSkinType} onChange={(e) => setForm({ ...form, targetSkinType: e.target.value })} /></Field><Field label={t('bundles.admin_target_hair')}><Input value={form.targetHairType} onChange={(e) => setForm({ ...form, targetHairType: e.target.value })} /></Field></div>
      <div className="grid gap-3 sm:grid-cols-2"><Field label={t('bundles.admin_description')}><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Field label={t('bundles.admin_description_rw')}><Textarea value={form.descriptionRw} onChange={(e) => setForm({ ...form, descriptionRw: e.target.value })} /></Field></div>
      <div><Label>{t('bundles.admin_cover')}</Label><div className="mt-2 flex items-center gap-2"><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void upload(event.target.files?.[0])} />{uploading && <Loader2 className="h-4 w-4 animate-spin" />}{form.coverImage && <button type="button" onClick={() => setForm({ ...form, coverImage: '', coverImageUrl: '' })} className="grid h-10 w-10 place-items-center"><X className="h-4 w-4" /></button>}</div></div>
      <div><Label>{t('bundles.admin_products')}</Label><div className="mt-2 max-h-56 space-y-2 overflow-y-auto rounded-xl border p-2">{products.map((product) => { const selected = form.products.find((item) => item.productId === product.id); return <div key={product.id} className="rounded-xl bg-gray-50 p-2"><label className="flex min-h-10 items-center gap-2"><Checkbox checked={Boolean(selected)} onCheckedChange={() => toggleProduct(product.id)} /><span className="min-w-0 flex-1 truncate text-sm font-semibold">{product.name}</span><span className="text-xs text-gray-500">{formatRWF(product.price)} · {product.stock}</span></label>{selected && <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5"><Input type="number" min="1" max="20" value={selected.quantity} onChange={(e) => updateProduct(product.id, { quantity: Number(e.target.value) })} /><Input type="number" min="0" value={selected.stepOrder} onChange={(e) => updateProduct(product.id, { stepOrder: Number(e.target.value) })} /><Input value={selected.stepLabel} onChange={(e) => updateProduct(product.id, { stepLabel: e.target.value })} placeholder={t('bundles.admin_step_en')} /><Input value={selected.stepLabelRw} onChange={(e) => updateProduct(product.id, { stepLabelRw: e.target.value })} placeholder={t('bundles.admin_step_rw')} /><label className="flex items-center gap-1 text-xs"><Checkbox checked={selected.isOptional} onCheckedChange={(value) => updateProduct(product.id, { isOptional: value === true })} />{t('bundles.optional')}</label></div>}</div>})}</div></div>
      <div className="grid gap-3 sm:grid-cols-2"><Field label={t('bundles.usage_title')}><Textarea value={form.usageInstructions} onChange={(e) => setForm({ ...form, usageInstructions: e.target.value })} /></Field><Field label={t('bundles.admin_usage_rw')}><Textarea value={form.usageInstructionsRw} onChange={(e) => setForm({ ...form, usageInstructionsRw: e.target.value })} /></Field></div>
      <div className="flex gap-4"><label className="flex items-center gap-2"><Checkbox checked={form.isActive} onCheckedChange={(value) => setForm({ ...form, isActive: value === true })} />{t('bundles.admin_active')}</label><label className="flex items-center gap-2"><Checkbox checked={form.isFeatured} onCheckedChange={(value) => setForm({ ...form, isFeatured: value === true })} />{t('bundles.admin_featured')}</label></div>
    </div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>{t('common.cancel')}</Button><Button onClick={save} disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{t('common.save')}</Button></DialogFooter></DialogContent></Dialog>
  </div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><Label>{label}</Label><div className="mt-1">{children}</div></div> }
