'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { Heart, Loader2, RefreshCw, ShoppingBag, Trash2 } from 'lucide-react'
import { formatRWF } from '@/lib/format'
import { useStore } from '@/store/useStore'
import { useT } from '@/lib/i18n/LanguageContext'
import IconButton from '@/components/a11y/IconButton'

interface Wish { id:string; productId:string; product:{ id:string;slug:string;name:string;price:number;images:string[];stock:number;brand?:{name:string}|null } }
export default function WishlistPage(){
 const t=useT()
 const [items,setItems]=useState<Wish[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const addToCart=useStore(s=>s.addToCart)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch('/api/wishlist',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||t('search.wishlist_failed'));setItems(d.wishlist||d.data?.wishlist||[])}catch(e){setError(e instanceof Error?e.message:t('search.wishlist_failed'))}finally{setLoading(false)}},[t]);useEffect(()=>{load()},[load])
 const remove=async(productId:string)=>{const r=await fetch('/api/wishlist',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId})});if(r.ok)setItems(v=>v.filter(i=>i.productId!==productId))}
 return <main className="min-h-screen bg-[#FAFAFA] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><span className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#B76E79]">{t('auth.saved_beauty')}</span><h1 className="mt-2 text-3xl font-bold">{t('nav.wishlist')}</h1><p className="mt-1 text-sm text-gray-500">{t('auth.wishlist_ready')}</p></div><Link href="/account" className="text-sm font-bold text-[#B76E79]">{t('orders.account_home')}</Link></div>{loading?<div className="grid min-h-80 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#B76E79]" /></div>:error?<div className="mt-8 rounded-xl bg-white p-10 text-center"><p className="font-bold">{error}</p><button onClick={load} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#1a1a1a] px-4 py-2 text-xs font-bold text-white"><RefreshCw className="h-4 w-4" />{t('common.retry')}</button></div>:items.length===0?<div className="mt-8 rounded-xl bg-white p-12 text-center shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><Heart className="mx-auto h-12 w-12 text-rose-200" /><h2 className="mt-4 text-xl font-bold">{t('empty.wishlist')}</h2><Link href="/products" className="mt-5 inline-block rounded-full bg-[#B76E79] px-5 py-2.5 text-sm font-bold text-white">{t('auth.discover_products')}</Link></div>:<div className="mt-7 grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3 lg:grid-cols-4">{items.map(item=>{const p=item.product;const image=p.images?.[0]||'';return <article key={item.id} className="group overflow-hidden rounded-xl border border-gray-100 bg-white shadow-[0_1px_3px_rgba(0,0,0,0.04)]"><Link href={`/products/${p.slug}`} className="block aspect-square overflow-hidden bg-gray-100">{image&&<img src={image} alt={p.name} className="h-full w-full object-cover transition-transform group-hover:scale-105" />}</Link><div className="p-3 sm:p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-400">{p.brand?.name||t('auth.freedom_beauty')}</p><Link href={`/products/${p.slug}`} className="mt-1 line-clamp-2 min-h-10 text-sm font-bold">{p.name}</Link><p className="mt-2 font-bold text-[#B76E79]">{formatRWF(p.price)}</p><div className="mt-3 flex gap-2"><button onClick={()=>addToCart({productId:p.id,slug:p.slug,name:p.name,price:p.price,image,stock:p.stock||99})} className="flex min-h-10 flex-1 items-center justify-center gap-1 rounded-xl bg-[#B76E79] text-xs font-bold text-white"><ShoppingBag className="h-3.5 w-3.5" />{t('product.add_to_cart')}</button><IconButton label={`${t('common.delete')}: ${p.name}`} icon={<Trash2 className="h-4 w-4" />} variant="danger" onClick={()=>remove(p.id)} className="rounded-xl border border-gray-200" /></div></div></article>})}</div>}</div></main>
}
