'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { Heart, Loader2, RefreshCw, ShoppingBag, Trash2 } from 'lucide-react'
import { formatRWF } from '@/lib/format'
import { useStore } from '@/store/useStore'

interface Wish { id:string; productId:string; product:{ id:string;slug:string;name:string;price:number;images:string[];stock:number;brand?:{name:string}|null } }
export default function WishlistPage(){
 const [items,setItems]=useState<Wish[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const addToCart=useStore(s=>s.addToCart)
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch('/api/wishlist',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load wishlist');setItems(d.wishlist||d.data?.wishlist||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load wishlist')}finally{setLoading(false)}},[]);useEffect(()=>{load()},[load])
 const remove=async(productId:string)=>{const r=await fetch('/api/wishlist',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId})});if(r.ok)setItems(v=>v.filter(i=>i.productId!==productId))}
 return <main className="min-h-screen bg-[#f8f9fa] px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><div className="flex items-end justify-between"><div><span className="text-[10px] font-black uppercase tracking-[0.2em] text-[#B76E79]">Saved beauty</span><h1 className="mt-2 text-3xl font-black">My wishlist</h1><p className="mt-1 text-sm text-gray-500">Products you love, ready when you are.</p></div><Link href="/account" className="text-sm font-bold text-[#B76E79]">Account home</Link></div>{loading?<div className="grid min-h-80 place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#B76E79]" /></div>:error?<div className="mt-8 rounded-3xl bg-white p-10 text-center"><p className="font-bold">{error}</p><button onClick={load} className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#1a1a1a] px-4 py-2 text-xs font-bold text-white"><RefreshCw className="h-4 w-4" />Retry</button></div>:items.length===0?<div className="mt-8 rounded-3xl bg-white p-12 text-center shadow-sm"><Heart className="mx-auto h-12 w-12 text-rose-200" /><h2 className="mt-4 text-xl font-black">Your wishlist is empty</h2><Link href="/products" className="mt-5 inline-block rounded-full bg-[#B76E79] px-5 py-2.5 text-sm font-bold text-white">Discover products</Link></div>:<div className="mt-7 grid grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3 lg:grid-cols-4">{items.map(item=>{const p=item.product;const image=p.images?.[0]||'';return <article key={item.id} className="group overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm"><Link href={`/products/${p.slug}`} className="block aspect-square overflow-hidden bg-gray-100">{image&&<img src={image} alt={p.name} className="h-full w-full object-cover transition-transform group-hover:scale-105" />}</Link><div className="p-3 sm:p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-gray-400">{p.brand?.name||'Freedom Beauty'}</p><Link href={`/products/${p.slug}`} className="mt-1 line-clamp-2 min-h-10 text-sm font-bold">{p.name}</Link><p className="mt-2 font-black text-[#B76E79]">{formatRWF(p.price)}</p><div className="mt-3 flex gap-2"><button onClick={()=>addToCart({productId:p.id,slug:p.slug,name:p.name,price:p.price,image,stock:p.stock||99})} className="flex min-h-10 flex-1 items-center justify-center gap-1 rounded-xl bg-[#B76E79] text-xs font-black text-white"><ShoppingBag className="h-3.5 w-3.5" />Add</button><button onClick={()=>remove(p.id)} className="grid h-10 w-10 place-items-center rounded-xl border border-gray-200 text-gray-400 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div></div></article>})}</div>}</div></main>
}
